// Canvas object types for Konva-based freeform drawing

export type ObjectType = 'stroke' | 'rectangle' | 'circle' | 'arrow' | 'line' | 'text' | 'sticker';

export type ToolType = 'pen' | 'rectangle' | 'circle' | 'arrow' | 'line' | 'text' | 'sticker' | 'select' | 'eraser';

// Base canvas object structure
export interface CanvasObject {
  id: string;
  canvas_id: string;
  type: ObjectType;
  data: Record<string, any>;
  style: Record<string, any>;
  transform?: Transform;
  created_by?: string;
  created_at?: string;
  updated_at?: string;
  z_index?: number;
  locked?: boolean;
}

// Transform properties
export interface Transform {
  x: number;
  y: number;
  scaleX?: number;
  scaleY?: number;
  rotation?: number;
}

// Stroke (freehand drawing) data
export interface StrokeData {
  points: number[][]; // [[x, y, pressure], ...]
  strokePoints?: number[][]; // Generated by perfect-freehand [[x, y], ...]
}

export interface StrokeStyle {
  color: string;
  size: number;
  thinning?: number;
  smoothing?: number;
  streamline?: number;
}

// Rectangle data
export interface RectangleData {
  width: number;
  height: number;
}

export interface RectangleStyle {
  fill?: string;
  stroke?: string;
  strokeWidth?: number;
  cornerRadius?: number;
}

// Circle data
export interface CircleData {
  radius: number;
}

export interface CircleStyle {
  fill?: string;
  stroke?: string;
  strokeWidth?: number;
}

// Line/Arrow data
export interface LineData {
  points: number[]; // [x1, y1, x2, y2]
}

export interface LineStyle {
  stroke: string;
  strokeWidth: number;
  lineCap?: 'butt' | 'round' | 'square';
}

// Text data
export interface TextData {
  text: string;
  fontSize: number;
  fontFamily: string;
  align?: 'left' | 'center' | 'right';
  width?: number;
}

export interface TextStyle {
  fill: string;
}

// Sticker data
export interface StickerData {
  stickerId: string;
  imageUrl: string;
  originalWidth: number;
  originalHeight: number;
}

// Canvas state
export interface Canvas {
  id: string;
  date: string;
  name?: string; // "the big bang" for first canvas, roman numerals for subsequent
  theme?: string;
  status: 'active' | 'archived';
  snapshot_url?: string;
  object_count: number;
  participant_count?: number;
}

// Sticker library
export interface Sticker {
  id: string;
  name: string;
  category: string;
  image_url: string;
  width: number;
  height: number;
  tags?: string[];
  active: boolean;
}

// Tool options
export interface PenOptions {
  color: string;
  size: number;
  thinning: number;
  smoothing: number;
  streamline: number;
}

export interface ShapeOptions {
  fill?: string;
  stroke: string;
  strokeWidth: number;
}

export interface TextOptions {
  fontSize: number;
  fontFamily: string;
  fill: string;
}
