import { Line } from 'react-konva';
import { flattenPoints } from '../../../utils/strokeHelpers';
import type { CanvasObject, StrokeData, StrokeStyle } from '../../../types/canvas.types';

interface StrokeObjectProps {
  object: CanvasObject;
}

export default function StrokeObject({ object }: StrokeObjectProps) {
  const data = object.data as StrokeData;
  const style = object.style as StrokeStyle;
  const transform = object.transform || { x: 0, y: 0 };

  // Use strokePoints if available (generated by perfect-freehand), otherwise use raw points
  const points = data.strokePoints || data.points;

  if (!points || points.length === 0) {
    return null;
  }

  // Flatten [[x,y], [x,y]] to [x, y, x, y] for Konva
  const flatPoints = flattenPoints(points);

  return (
    <Line
      points={flatPoints}
      stroke={style.color}
      strokeWidth={0.5}
      tension={0}
      lineCap="round"
      lineJoin="round"
      fill={style.color}
      closed={!!data.strokePoints} // Close path if using perfect-freehand
      {...transform}
    />
  );
}
